spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/barberhub
    username: barberhub
    password: barberhub123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: minha-chave-super-secreta-com-mais-de-32-caracteres-123456barberhub-secret-key-super-safe
  expiration: 86400000